name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
        project_id: gd-gcp-gridu-devops-t1-t2
        export_default_credentials: true

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve

  deploy-dev:
    needs: terraform-apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gd-gcp-gridu-devops-t1-t2
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Authenticate Kubectl
        run: gcloud container clusters get-credentials nkuzman-dev --region us-central1 --project gd-gcp-gridu-devops-t1-t2

      - name: Apply Kubernetes Manifests (DEV)
        run: |
          kubectl apply -f deploy/kubernetes/complete-demo.yaml

  deploy-staging:
    needs: terraform-apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gd-gcp-gridu-devops-t1-t2
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Authenticate Kubectl
        run: gcloud container clusters get-credentials nkuzman-staging --region us-central1 --project gd-gcp-gridu-devops-t1-t2

      - name: Apply Kubernetes Manifests (STAGING)
        run: |
          kubectl apply -f deploy/kubernetes/complete-demo.yaml

  deploy-production:
    needs: terraform-apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gd-gcp-gridu-devops-t1-t2
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Authenticate Kubectl
        run: gcloud container clusters get-credentials nkuzman-prod --region us-central1 --project gd-gcp-gridu-devops-t1-t2

      - name: Apply Kubernetes Manifests (PRODUCTION)
        run: |
          gcloud components install gke-gcloud-auth-plugin
          kubectl apply -f deploy/kubernetes/complete-demo.yaml
